FROM openjdk:11-jdk-slim AS jar

RUN addgroup --system spring && adduser --system spring --ingroup spring

USER spring:spring

RUN mkdir -p /tmp/logs && chown spring:spring /tmp/logs

COPY --chown=spring target/*.jar /app.jar

VOLUME /tmp/logs

ENTRYPOINT ["java", "-jar", "/app.jar"]